<?xml version="1.0" standalone="yes"?>
<!DOCTYPE BAM 
[
<!ELEMENT BAM (modelName,
               modelDescr,
               rxnName+,
               substrate+,
               particulate+,
               time,
               numGrid,
               detach,
               flow,
               unit+,
               sliders?,
               numCoeff)>

<!ELEMENT modelName (#PCDATA)>

<!ELEMENT modelDescr (#PCDATA)>

<!ELEMENT rxnName (#PCDATA)>

<!ELEMENT substrate (rxnData+, biocide?)>
<!ATTLIST substrate name    CDATA   #REQUIRED
                    abbr    CDATA   #REQUIRED
                    diff    CDATA   #REQUIRED>

<!ELEMENT particulate (rxnData+)>
<!ATTLIST particulate name    CDATA   #REQUIRED
                      abbr    CDATA   #REQUIRED
                      rho     CDATA   #REQUIRED>

<!ELEMENT rxnData EMPTY>
<!ATTLIST rxnData stoich      CDATA               #REQUIRED
                  law         (ZeroOrder|FirstOrder|HalfOrder|Monod|Inhibition|Blackman|ChenBiocide)  #REQUIRED
                  coeff       CDATA               #REQUIRED>

<!ELEMENT time EMPTY>
<!ATTLIST time init   CDATA  #REQUIRED
               final  CDATA  #REQUIRED
               step   CDATA  #REQUIRED>

<!ELEMENT numGrid (#PCDATA)>

<!ELEMENT detach EMPTY>
<!ATTLIST detach coeff1  CDATA  #REQUIRED
                 coeff2  CDATA  #REQUIRED
                 coeff3  CDATA  #REQUIRED
                 coeff4  CDATA  #REQUIRED
                 coeff5  CDATA  #REQUIRED>

<!ELEMENT biocide EMPTY>
<!ATTLIST biocide conc      CDATA  #REQUIRED
                  begin     CDATA  #REQUIRED
                  duration  CDATA  #REQUIRED
                  freq      CDATA  #REQUIRED
                  det       CDATA  #REQUIRED
                  pulseStep (Pulse|Step)  #REQUIRED>

<!ELEMENT flow EMPTY>
<!ATTLIST flow time1    CDATA  #REQUIRED
               flow1    CDATA  #REQUIRED
               time2    CDATA  #REQUIRED
               flow2    CDATA  #REQUIRED
               time2    CDATA  #REQUIRED
               flow2    CDATA  #REQUIRED
               time3    CDATA  #REQUIRED
               flow3    CDATA  #REQUIRED
               time4    CDATA  #REQUIRED
               flow4    CDATA  #REQUIRED
               time5    CDATA  #REQUIRED
               flow5    CDATA  #REQUIRED>

<!ELEMENT unit (geometry,
                initSubstrate+,
                initParticulate+)>

<!ATTLIST unit initThickness  CDATA  #REQUIRED
               fixCalc        (Fixed|Calculate)  #REQUIRED>

<!ELEMENT geometry EMPTY>
<!ATTLIST geometry area       CDATA  #REQUIRED
                   thickness  CDATA  #REQUIRED
                   vol        CDATA  #REQUIRED
                   voidFrac   CDATA  #REQUIRED
                   diff       CDATA  #REQUIRED
                   rate       CDATA  #REQUIRED>

<!ELEMENT initSubstrate EMPTY>
<!ATTLIST initSubstrate inletConc  CDATA  #REQUIRED
                        bulkConc   CDATA  #REQUIRED
                        fixCalc    (Fixed|Calculate)  #REQUIRED>

<!ELEMENT initParticulate EMPTY>
<!ATTLIST initParticulate inletConc  CDATA  #REQUIRED
                          bulkConc   CDATA  #REQUIRED
                          voidFrac   CDATA  #REQUIRED>

<!ELEMENT sliders (subSlider+,
                   flowSlider,
                   detachSlider,
                   thicknessSlider)>

<!ELEMENT subSlider EMPTY>
<!ATTLIST subSlider min    CDATA  #REQUIRED
                    max    CDATA  #REQUIRED
                    major  CDATA  #REQUIRED
                    minor  CDATA  #REQUIRED>
                
<!ELEMENT flowSlider EMPTY>
<!ATTLIST flowSlider current CDATA  #REQUIRED
					 min     CDATA  #REQUIRED
                     max     CDATA  #REQUIRED
                     major   CDATA  #REQUIRED
                     minor   CDATA  #REQUIRED>
                
<!ELEMENT detachSlider EMPTY>
<!ATTLIST detachSlider min    CDATA  #REQUIRED
                       max    CDATA  #REQUIRED
                       major  CDATA  #REQUIRED
                       minor  CDATA  #REQUIRED>
                
<!ELEMENT thicknessSlider EMPTY>
<!ATTLIST thicknessSlider min    CDATA  #REQUIRED
                          max    CDATA  #REQUIRED
                          major  CDATA  #REQUIRED
                          minor  CDATA  #REQUIRED>

<!ELEMENT numCoeff EMPTY>
<!ATTLIST numCoeff stol  CDATA  #REQUIRED
                   ntol  CDATA  #REQUIRED>

]>
<BAM>
   <modelName>Default BAM Model</modelName>
   <modelDescr>Default BAM Model description ...</modelDescr>

<!-- Reaction Names -->
   <rxnName>Growth</rxnName>
   <rxnName>Biocide w/live</rxnName>
   <rxnName>Biocide w/dead</rxnName>
   <rxnName>Disinfection</rxnName>

<!-- Substrate Definitions -->
   <substrate name="Glucose" abbr="Glu" diff="+5.70000e-04">
      <rxnData stoich="-2.22000e+00" law="Monod" coeff="+2.55000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
   </substrate>

   <substrate name="Biocide" abbr="Bio" diff="+1.50000e-04">
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+6.00000e+01"></rxnData>
      <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+6.00000e+01"></rxnData>
      <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="+1.00000e+02"></rxnData>
   <biocide conc="+0.00000e+00"
            begin="+0.00000e+00"
            duration="+0.00000e+00"
            freq="+9.99000e+02"
            det="+0.00000e+00"
            pulseStep="Step"/>
   </substrate>

<!-- Particulate Definitions -->
   <particulate name="Pseudomonas" abbr="Pse" rho="+3.00000e+04">
      <rxnData stoich="+1.00000e+00" law="FirstOrder" coeff="+7.50000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+1.00000e+00"></rxnData>
   </particulate>

   <particulate name="Dead cells" abbr="Dea" rho="+3.00000e+04">
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="+1.00000e+00"></rxnData>
      <rxnData stoich="+1.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"></rxnData>
   </particulate>



<!-- Initial Conditions -->
   <time init="+0.00000e+00" final="+1.00000e+01" step="+1.00000e-01"/>

   <numGrid>5</numGrid>

   <detach coeff1="96000"
           coeff2="0"
           coeff3="0"
           coeff4="0"
           coeff5="0"/>


   <flow time1="+0.00000e+00"  flow1="+1.00000e00"
         time2="+9.99000e+02"  flow2="+0.00000e00"
         time3="+9.99000e+02"  flow3="+0.00000e00"
         time4="+9.99000e+02"  flow4="+0.00000e00"
         time5="+9.99000e+02"  flow5="+0.00000e00"/>

<!-- Unit 1 -->
   <unit initThickness="5.0E-5" fixCalc="Calculate">

     <geometry area="1.0"
               thickness="1.05E-4"
               vol="0.1"
               voidFrac="0.885"
               diff="0.8"
               rate="0.0"/>

     <initSubstrate inletConc="+0.00000e+01"
                    bulkConc="+0.00000e+00"
                    fixCalc="Calculate"/>

     <initSubstrate inletConc="+4.00000e+00"
                    bulkConc="+0.00000e+00"
                    fixCalc="Calculate"/>

     <initParticulate inletConc="+0.00000e+01"
                      bulkConc="+0.00000e+00"
                      voidFrac="0.1149997"/>

     <initParticulate inletConc="+0.00000e+01"
                      bulkConc="+0.00000e+00"
                      voidFrac="1.0e-8"/>

   </unit>
<!-- End Unit 1 -->

<!-- Numerical Coefficients -->
   <numCoeff stol="1.00000e-07" ntol="5.00000e-04"/>

</BAM>
