=== markowkes/BiofilmModel/BAM-2019/BAM-2019/xml/bam.dtd
<!-- This DTD defines the format of a Bam model definition.-->

<!-- ============================================================== -->
<!-- BAM                                                            -->
<!-- ============================================================== -->

<!ELEMENT BAM (modelName,
               modelDescr,
               rxnName+,
               substrate+,
               particulate+,
               time,
               numGrid,
               detach,
               flow,
               unit+,
               sliders?,
               numCoeff)>

<!ELEMENT modelName (#PCDATA)>

<!ELEMENT modelDescr (#PCDATA)>

<!ELEMENT rxnName (#PCDATA)>

<!ELEMENT substrate (rxnData+, biocide?)>
<!ATTLIST substrate name    CDATA   #REQUIRED
                    abbr    CDATA   #REQUIRED
                    diff    CDATA   #REQUIRED>

<!ELEMENT particulate (rxnData+)>
<!ATTLIST particulate name    CDATA   #REQUIRED
                      abbr    CDATA   #REQUIRED
                      rho     CDATA   #REQUIRED>

<!ELEMENT rxnData EMPTY>
<!ATTLIST rxnData stoich      CDATA               #REQUIRED
                  law         (ZeroOrder|FirstOrder|HalfOrder|Monod|Inhibition|Blackman|ChenBiocide)  #REQUIRED
                  coeff       CDATA               #REQUIRED>

<!ELEMENT time EMPTY>
<!ATTLIST time init   CDATA  #REQUIRED
               final  CDATA  #REQUIRED
               step   CDATA  #REQUIRED>

<!ELEMENT numGrid (#PCDATA)>

<!ELEMENT detach EMPTY>
<!ATTLIST detach coeff1  CDATA  #REQUIRED
                 coeff2  CDATA  #REQUIRED
                 coeff3  CDATA  #REQUIRED
                 coeff4  CDATA  #REQUIRED
                 coeff5  CDATA  #REQUIRED>

<!ELEMENT biocide EMPTY>
<!ATTLIST biocide conc      CDATA  #REQUIRED
                  begin     CDATA  #REQUIRED
                  duration  CDATA  #REQUIRED
                  freq      CDATA  #REQUIRED
                  det       CDATA  #REQUIRED
                  pulseStep (Pulse|Step)  #REQUIRED>

<!ELEMENT flow EMPTY>
<!ATTLIST flow time1    CDATA  #REQUIRED
               flow1    CDATA  #REQUIRED
               time2    CDATA  #REQUIRED
               flow2    CDATA  #REQUIRED
               time2    CDATA  #REQUIRED
               flow2    CDATA  #REQUIRED
               time3    CDATA  #REQUIRED
               flow3    CDATA  #REQUIRED
               time4    CDATA  #REQUIRED
               flow4    CDATA  #REQUIRED
               time5    CDATA  #REQUIRED
               flow5    CDATA  #REQUIRED>

<!ELEMENT unit (geometry,
                initSubstrate+,
                initParticulate+)>

<!ATTLIST unit initThickness  CDATA  #REQUIRED
               fixCalc        (Fixed|Calculate)  #REQUIRED>

<!ELEMENT geometry EMPTY>
<!ATTLIST geometry area       CDATA  #REQUIRED
                   thickness  CDATA  #REQUIRED
                   vol        CDATA  #REQUIRED
                   voidFrac   CDATA  #REQUIRED
                   diff       CDATA  #REQUIRED
                   rate       CDATA  #REQUIRED>

<!ELEMENT initSubstrate EMPTY>
<!ATTLIST initSubstrate inletConc  CDATA  #REQUIRED
                        bulkConc   CDATA  #REQUIRED
                        fixCalc    (Fixed|Calculate)  #REQUIRED>

<!ELEMENT initParticulate EMPTY>
<!ATTLIST initParticulate inletConc  CDATA  #REQUIRED
                          bulkConc   CDATA  #REQUIRED
                          voidFrac   CDATA  #REQUIRED>

<!ELEMENT sliders (subSlider+,
                   flowSlider,
                   detachSlider,
                   thicknessSlider)>

<!ELEMENT subSlider EMPTY>
<!ATTLIST subSlider min    CDATA  #REQUIRED
                    max    CDATA  #REQUIRED
                    major  CDATA  #REQUIRED
                    minor  CDATA  #REQUIRED>
                
<!ELEMENT flowSlider EMPTY>
<!ATTLIST flowSlider current CDATA #REQUIRED
					 min     CDATA  #REQUIRED
                     max     CDATA  #REQUIRED
                     major   CDATA  #REQUIRED
                     minor   CDATA  #REQUIRED>
                
<!ELEMENT detachSlider EMPTY>
<!ATTLIST detachSlider min    CDATA  #REQUIRED
                       max    CDATA  #REQUIRED
                       major  CDATA  #REQUIRED
                       minor  CDATA  #REQUIRED>
                
<!ELEMENT thicknessSlider EMPTY>
<!ATTLIST thicknessSlider min    CDATA  #REQUIRED
                          max    CDATA  #REQUIRED
                          major  CDATA  #REQUIRED
                          minor  CDATA  #REQUIRED>
                       
<!ELEMENT numCoeff EMPTY>
<!ATTLIST numCoeff stol  CDATA  #REQUIRED
                   ntol  CDATA  #REQUIRED>

=== markowkes/BiofilmModel/BAM-2019/BAM-2019/xml/Growth+consump+disinf-PSS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BAM SYSTEM "bam.dtd">

<BAM>
  <modelName>Catalase Protection from Hydrogen Peroxide in a Biofilm</modelName>
  <modelDescr>Default BAM Model description ...</modelDescr>
  <rxnName>Growth</rxnName>
  <rxnName>Consumption w/ Live</rxnName>
  <rxnName>Consumption w/ Dead</rxnName>
  <rxnName>Disinfection</rxnName>
  <substrate name="Glucose" abbr="Glu" diff="+5.70000e-04">
    <rxnData stoich="-2" law="Monod" coeff="2.55"/>
    <rxnData stoich="0" law="ZeroOrder" coeff="1"/>
    <rxnData stoich="0" law="ZeroOrder" coeff="1"/>
    <rxnData stoich="0" law="ZeroOrder" coeff="1"/>
  </substrate>
  <substrate name="Hydrogen Peroxide" abbr="H2O2" diff="1.728E-4">
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="-1" law="FirstOrder" coeff="5"/>
    <rxnData stoich="-1" law="FirstOrder" coeff="5"/>
    <rxnData stoich="0" law="FirstOrder" coeff="1"/>
    <biocide conc="1700" begin="2" duration="2" freq="4" det="0" pulseStep="Pulse"/>
  </substrate>
  <particulate name="Dead cells" abbr="Dead" rho="2.5e5">
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="1"/>
    <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="1"/>
    <rxnData stoich="+1" law="ZeroOrder" coeff="1"/>
  </particulate>
  <particulate name="Pseudomonas aeruginosa" abbr="Pse" rho="2.5e5">
    <rxnData stoich="1" law="FirstOrder" coeff="7.5"/>
    <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="1"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="1"/>
    <rxnData stoich="-1" law="FirstOrder" coeff="2"/>
  </particulate>
  <time init="+0.00000e+00" final="+1.00000e+01" step="1e-2"/>
  <numGrid>9</numGrid>
  <detach coeff1="15000" coeff2="0" coeff3="0" coeff4="0" coeff5="0"/>
  <flow time1="+0.00000e+00" flow1="+1.00000e00" time2="+9.99000e+02" flow2="+0.00000e00" time3="+9.99000e+02" flow3="+0.00000e00" time4="+9.99000e+02" flow4="+0.00000e00" time5="+9.99000e+02" flow5="+0.00000e00"/>
  <unit initThickness="5.0E-5" fixCalc="Calculate">
    <geometry area="1.0" thickness="1e-5" vol="0.1" voidFrac="0.92" diff="0.45" rate="0.0"/>
    <initSubstrate inletConc="53" bulkConc="+0.00000e+00" fixCalc="Calculate"/>
    <initSubstrate inletConc="0" bulkConc="+0.00000e+00" fixCalc="Calculate"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="1e-8"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="0.08"/>
  </unit>
  <numCoeff stol="0.00" ntol="0.00"/>
</BAM>

=== markowkes/BiofilmModel/BAM-2019/BAM-2019/xml/applet/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BAM SYSTEM "bam.dtd">

<BAM>
  <modelName>Test BAM model </modelName>
  <modelDescr>Test BAM Model description with slider specifications.  The sliders are used in the hypertextbook interactive model.</modelDescr>
  <rxnName>Growth</rxnName>
  <rxnName>Biocide w/live</rxnName>
  <rxnName>Biocide w/dead</rxnName>
  <rxnName>Disinfection</rxnName>
  <substrate name="Glucose" abbr="Glu" diff="+5.70000e-04">
    <rxnData stoich="-2.22000e+00" law="Monod" coeff="+2.55000e+00"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
  </substrate>
  <substrate name="Biocide" abbr="Bio" diff="+1.50000e-04">
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+6.00000e+01"/>
    <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+6.00000e+01"/>
    <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="+1.00000e+02"/>
    <biocide conc="+0.00000e+00" begin="+0.00000e+00" duration="+0.00000e+00" freq="+9.99000e+02" det="+0.00000e+00" pulseStep="Step"/>
  </substrate>
  <particulate name="Pseudomonas" abbr="Pse" rho="+3.00000e+04">
    <rxnData stoich="+1.00000e+00" law="FirstOrder" coeff="+7.50000e+00"/>
    <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+1.00000e+00"/>
  </particulate>
  <particulate name="Dead cells" abbr="Dea" rho="+3.00000e+04">
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+0.00000e+00" law="FirstOrder" coeff="+1.00000e+00"/>
    <rxnData stoich="+1.00000e+00" law="ZeroOrder" coeff="+1.00000e+00"/>
  </particulate>
  <time init="+0.00000e+00" final="+1.00000e+01" step="+1.00000e-01"/>
  <numGrid>5</numGrid>
  <detach coeff1="96000" coeff2="0" coeff3="0" coeff4="0" coeff5="0"/>
  <flow time1="+0.00000e+00" flow1="+1.00000e00" time2="+9.99000e+02" flow2="+0.00000e00" time3="+9.99000e+02" flow3="+0.00000e00" time4="+9.99000e+02" flow4="+0.00000e00" time5="+9.99000e+02" flow5="+0.00000e00"/>
  <unit initThickness="5.0E-5" fixCalc="Calculate">
    <geometry area="1.0" thickness="1.05E-4" vol="0.1" voidFrac="0.885" diff="0.8" rate="0.0"/>
    <initSubstrate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" fixCalc="Calculate"/>
    <initSubstrate inletConc="+4.00000e+00" bulkConc="+0.00000e+00" fixCalc="Calculate"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="0.1149997"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="1.0e-8"/>
  </unit>
  <sliders>
    <subSlider min="0" max="20" major="10" minor="5"/>
    <subSlider min="0" max="20" major="10" minor="5"/>
    <flowSlider current="10" min="1" max="21" major="10" minor="5"/>
    <detachSlider min="70000" max="130000" major="20000" minor="10000"/>
    <thicknessSlider min="0" max="50" major="10" minor="5"/>
  </sliders>
  <numCoeff stol="0.00" ntol="0.00"/>
</BAM>

=== markowkes/BiofilmModel/BAM-2019/BAM-2019/xml/mccarty HW6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BAM SYSTEM "bam.dtd">

<BAM>
  <modelName>McCarty HW6</modelName>
  <modelDescr>Demo case for BAM instruction</modelDescr>
  <rxnName>Growth</rxnName>
  <rxnName>Decay</rxnName>
  <substrate name="Methanol" abbr="Meth" diff="6.9e-5">
    <rxnData stoich="-2.646e0" law="Monod" coeff="1e0"/>
    <rxnData stoich="0" law="ZeroOrder" coeff="1e0"/>
  </substrate>
  <particulate name="Dead" abbr="Dead" rho="2.5e5">
    <rxnData stoich="0" law="ZeroOrder" coeff="1e0"/>
    <rxnData stoich="1e0" law="ZeroOrder" coeff="1e0"/>
  </particulate>
  <particulate name="Live" abbr="Live" rho="2.5e5">
    <rxnData stoich="1e0" law="FirstOrder" coeff="2"/>
    <rxnData stoich="-1e0" law="FirstOrder" coeff="1e-1"/>
  </particulate>
  <time init="+0.00000e+00" final="+1.00000e+01" step="+1.00000e-01"/>
  <numGrid>12</numGrid>
  <detach coeff1="20000" coeff2="0" coeff3="0" coeff4="0" coeff5="0"/>
  <flow time1="+0.00000e+00" flow1="+1.00000e00" time2="+9.99000e+02" flow2="+0.00000e00" time3="+9.99000e+02" flow3="+0.00000e00" time4="+9.99000e+02" flow4="+0.00000e00" time5="+9.99000e+02" flow5="+0.00000e00"/>
  <unit initThickness="1.0e-5" fixCalc="Calculate">
    <geometry area="1.0" thickness="1e7" vol="0.1" voidFrac="0.92" diff="0.5" rate="0.0"/>
    <initSubstrate inletConc="+1.00000e+02" bulkConc="+1.00000e+02" fixCalc="Calculate"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="1.0e-8"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="0.08"/>
  </unit>
  <numCoeff stol="0.00" ntol="0.00"/>
</BAM>

=== markowkes/BiofilmModel/BAM-2019/BAM-2019/xml/Stewart-HW5-10-27-21.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BAM SYSTEM "bam.dtd">

<BAM>
  <modelName>BAM Demo</modelName>
  <modelDescr>Demo case for BAM instruction</modelDescr>
  <rxnName>Growth</rxnName>
  <rxnName>Decay</rxnName>
  <substrate name="Methanol" abbr="CH3OH" diff="+1.380000e-04">
    <rxnData stoich="-2.64600e+00" law="Monod" coeff="+1.0000e+00"/>
    <rxnData stoich="0" law="ZeroOrder" coeff="+1.0000e+00"/>
  </substrate>
  <substrate name="Biocide" abbr="bio" diff="+1.380000e-04">
    <rxnData stoich="-2.64600e+00" law="Monod" coeff="+1.0000e+00"/>
    <rxnData stoich="0" law="ZeroOrder" coeff="+1.0000e+00"/>
    <biocide conc="0" begin="0" duration="0" freq="999" det="0" pulseStep="Step"/>
  </substrate>
  <particulate name="Live" abbr="Live" rho="2.5e5">
    <rxnData stoich="+1.00000e+00" law="FirstOrder" coeff="+2.00000e+00"/>
    <rxnData stoich="-1.00000e+00" law="FirstOrder" coeff="+0.1000e+00"/>
  </particulate>
  <particulate name="Dead" abbr="Dead" rho="2.5e5">
    <rxnData stoich="+0.00000e+00" law="ZeroOrder" coeff="1"/>
    <rxnData stoich="+1.00000e+00" law="ZeroOrder" coeff="1"/>
  </particulate>
  <time init="+0.00000e+00" final="+1.00000e+02" step="+1.00000e-01"/>
  <numGrid>12</numGrid>
  <detach coeff1="1980" coeff2="0" coeff3="0" coeff4="0" coeff5="0"/>
  <flow time1="+0.00000e+00" flow1="+1.00000e00" time2="+9.99000e+02" flow2="+0.00000e00" time3="+9.99000e+02" flow3="+0.00000e00" time4="+9.99000e+02" flow4="+0.00000e00" time5="+9.99000e+02" flow5="+0.00000e00"/>
  <unit initThickness="5.0e-6" fixCalc="Calculate">
    <geometry area="1.0" thickness="1.0E-5" vol="0.1" voidFrac="0.92" diff="0.5" rate="0.0"/>
    <initSubstrate inletConc="+25" bulkConc="25" fixCalc="Calculate"/>
    <initSubstrate inletConc="+25" bulkConc="25" fixCalc="Calculate"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="0.08"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="1.0e-8"/>
  </unit>
  <numCoeff stol="0.00" ntol="0.00"/>
</BAM>

=== markowkes/BiofilmModel/BAM-2019/BAM-2019/xml/stewart-demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BAM SYSTEM "bam.dtd">

<BAM>
  <modelName>BAM Demo</modelName>
  <modelDescr>Demo case for BAM instruction</modelDescr>
  <rxnName>Growth</rxnName>
  <substrate name="Glucose" abbr="Glu" diff="+5.70000e-04">
    <rxnData stoich="-2.22000e+00" law="Monod" coeff="+2.55000e+00"/>
  </substrate>
  <particulate name="Live" abbr="Live" rho="2.5e5">
    <rxnData stoich="+1.00000e+00" law="FirstOrder" coeff="+7.50000e+00"/>
  </particulate>
  <time init="+0.00000e+00" final="+1.00000e+01" step="+1.00000e-01"/>
  <numGrid>12</numGrid>
  <detach coeff1="20000" coeff2="0" coeff3="0" coeff4="0" coeff5="0"/>
  <flow time1="+0.00000e+00" flow1="+1.00000e00" time2="+9.99000e+02" flow2="+0.00000e00" time3="+9.99000e+02" flow3="+0.00000e00" time4="+9.99000e+02" flow4="+0.00000e00" time5="+9.99000e+02" flow5="+0.00000e00"/>
  <unit initThickness="1.0e-5" fixCalc="Calculate">
    <geometry area="1.0" thickness="1.05E-4" vol="0.1" voidFrac="0.92" diff="0.5" rate="0.0"/>
    <initSubstrate inletConc="+1.00000e+02" bulkConc="+1.00000e+02" fixCalc="Calculate"/>
    <initParticulate inletConc="+0.00000e+01" bulkConc="+0.00000e+00" voidFrac="0.08"/>
  </unit>
  <numCoeff stol="0.00" ntol="0.00"/>
</BAM>
